name: secrets_workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "movies" branch
  push:
    branches: [ "movies" ]
    paths:
      - '.github/workflows/secrets_workflow.yml'
  pull_request:
    branches: [ "movies" ]
    paths:
      - '.github/workflows/secrets_workflow.yml'
    
  workflow_dispatch:
env:
  name: "usman's"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  greeting_job_secret:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use secrets in workflow
        run: echo "Greeting Secrets: ${{ secrets.GREETING_SECRETS}}"
        run: echo "${{ secrets.GREETING_SECRETS}}, from the $name account!"
