name: variable_workflow

# Controls when the workflow will run
on:
  workflow_dispatch:
env:
  name: "usman's"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
 
    steps:
      - name: Say Hello job
        run: echo "$Greeting, from the $name account!"
